export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_TEACHER = "SET_CURRENT_TEACHER";
export const SET_CURRENT_SELECTED_TEACHER = "SET_CURRENT_SELECTED_TEACHER";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";
export const SET_FACULTY = "SET_FACULTY";
export const SET_INTERNSHIPS = "SET_INTERNSHIPS";
export const SET_CURRENT_INTERNSHIP = "SET_CURRENT_INTERNSHIP";
export const SET_NOTICES = "SET_NOTICES";

export const SET_STUDENTS_NOTICES = "SET_STUDENTS_NOTICES";
export const SET_CURRENT_SELECTED_ADMIN = "SET_CURRENT_SELECTED_ADMIN";

export const GET_FACULTY_PROFILE="GET_FACULTY_PROFILE";
export const SET_CURRENT_SELECTED_FACULTY="SET_CURRENT_SELECTED_FACULTY";
export const FORWARD_INTERNSHIP="FORWARD_INTERNSHIP";