export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_TEACHER = "SET_CURRENT_TEACHER";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";
export const SET_INTERNSHIPS = "SET_INTERNSHIPS";
export const SET_CURRENT_INTERNSHIP = "SET_CURRENT_INTERNSHIP";
